---
- name: Get geerlingguy.dotfiles
  command: ansible-galaxy install geerlingguy.dotfiles
  register: geerlingguy
  changed_when: "'is already installed' not in geerlingguy.stderr"
  failed_when: "'ERROR' in geerlingguy.stderr"

- name: Ensures cherrytree config directory exists
  file: 
    path: "{{ homefolder + '.config/cherrytree' }}"
    state: "directory"

- name: Include geerlingguy.dotfiles
  include_role:
    name: geerlingguy.dotfiles
